name: Test

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}}
    strategy:
      matrix:
        otp: [20.3, 21.3, 22.1, 23.1]
        include:
          - otp: '20.3'
            rebar: '3.15.2'
          - otp: '21.3'
            rebar: '3.15.2'
          - otp: '22.1'
            rebar: '3.17.0'
          - otp: '23.1'
            rebar: '3.17.0'
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: ErlGang/setup-erlang@master
        with:
          otp-version: ${{matrix.otp}}
      - run: curl -LO https://github.com/erlang/rebar3/releases/download/${{matrix.rebar}}/rebar3
      - run: chmod +x rebar3
      - run: ./rebar3 do compile, dialyzer, eunit, ct
